# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-01 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isbn',
            field=models.CharField(default='978-0545139700', max_length=50),
        ),
    ]
